apiVersion: apps/v1
kind: Deployment
metadata: 
  name: meudeployment
spec:
  replicas: 4
  selector:
    matchLabels:
      app: web
  template:
    metadata: 
      name: meupod-conversao
      labels:
        app: web
    spec:
      containers:
      - name: site
        image: amaurijr1976/conversao-temperatura:v1
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata: 
  name: web-page
spec:
  selector:
    app: web
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001
  type: NodePort
    